### ISSUE TITLE
Some Tags cannot be parsed with versions after 2.8

### ISSUE THREAD

**Issue by qbiecom** [yermak/AudioBookConverter#20] opened 2019-01-01 21:40 UTC
Hi!

I recently found your software after someone posted about it on reddit. Great work! It's really helped me convert a lot of MP3s into AudioBook format for my iPod Touch.

However, for some of my files I find that I've had to downgrade to version 2.8 in order to convert them. In versions higher than this, I can add the files to the list however it doesn't read the tags (so it's not auto-filling in the information) and then the application just hangs when I try to start the conversion process. I've had a quick look at the tags and I can't see anything obviously different between a working and non-working file.

I assume this is due to the switch to the javafx.media API in version 2.9, so it might be worth either seeing if you can fix it, or maybe have an option to fallback to ffprobe if needed?

I can provide a sample file if required - don't want to post it publicly however as it's a copyrighted work.

**Comment by yermak** [comment] 2019-01-02 09:59
Hi!
Thanks for feedback, it's really important.

You are right javafx.media API seems to be broken, I also could not find a root cause of the issue. However, for most of the files it worked and it gave slightly better perfromance (as no need to launch ffprobe each time).
Using javafx.media allawed to play back files (kind of preview) prior to encoding which is usuful for re-ordring chapters or understanding book number in the series.

I will check shortly how to revert safely.

**Comment by yermak** [comment] 2019-01-02 15:40
Fixed in 3.1

**Closed by yermak** 2019-01-02 15:40 UTC
