### ISSUE TITLE
Chapter duration missing from first chapter in list

### ISSUE THREAD

**Issue by runningfree73** [yermak/AudioBookConverter#395] opened 2022-05-29 09:50 UTC
When editing an audiobook's chapters to include duration, the duration is missing from the first chapter. Only the hyphen is showing, then a blank space where the duration should be. The duration displays correctly for all subsequent chapters in the list.

![screenshot](https://user-images.githubusercontent.com/21579173/170862022-69b74ffb-db6a-4ddb-aa78-ce23f15a72ea.png)
.

**Comment by yermak** [comment] 2022-06-02 07:54
@runningfree73 , is it repeatable? Does it always happens on any files or just happened once?

I can not reproduce it, seems like formatting error, but it's not quite clear why...

If you can repeatedly can reproduce it please let me know

**Comment by runningfree73** [comment] 2022-06-08 00:23
I'm getting mixed results. With .mp3 files it's working as expected but just now when importing an .m4b file the duration isn't showing for any of the chapters whereas before it was just the first chapter.

**Comment by yermak** [comment] 2022-06-08 07:01
@runningfree73 , 
if you can confirm that it works for mp3 files, but there are problems with importing m4b files this narrows the search of an issue. 
Thanks, i will have a look into it.

**Comment by runningfree73** [comment] 2022-06-08 07:26
Yes, I can confirm that's the case at least from the limited amount of testing I've done so far.

**Comment by yermak** [comment] 2024-06-06 07:58
fixed issue in m4b import. Can't reproduce it on mp3.
Will be released in version after 6.5.0

**Closed by yermak** 2024-06-06 07:58 UTC
Labels: bug
