### ISSUE TITLE
doesn't start

### ISSUE THREAD

**Issue by joespinoza** [yermak/AudioBookConverter#602] opened 2024-06-05 06:55 UTC
the program doesn't open.

I had version 6.4.1 (for windows) and updated to 6.5.0

**Comment by yermak** [comment] 2024-06-05 14:00
removed the build. will check later today

**Comment by yermak** [comment] 2024-06-05 20:08
Which build did you use? Just retested Portable version works fine.

**Comment by joespinoza** [comment] 2024-06-05 20:14
firts the "single user", then i tried the "all users" but neither work

**Comment by yermak** [comment] 2024-06-06 11:31
Could you please check portable version?
I will check installers...

**Comment by joespinoza** [comment] 2024-06-06 15:29
didn't work portable version, neither "single user" 6.5.1

**Comment by tschroeder13** [comment] 2024-06-09 20:08
Hey, had the same issue. Steam app (6..4.1) not starting, switched to GitHub portable release 6.5.1 - same thing here.

**Comment by joespinoza** [comment] 2024-06-11 05:10
> Could you please check portable version? I will check installers...

Any update?

**Comment by Nepumuk2000** [comment] 2024-06-11 14:55
Same problem here on Surface Win 11 Pro. The 6.5.1 all users won't start...

**Comment by SeMuh83** [comment] 2024-06-12 14:35
Same issue here

Old version 6.2... was working

6.5.1 all users/portable not working.
Is not starting

**Comment by fabiwan** [comment] 2024-06-12 17:53
> All works when i test. Could you run app from console and show if there is any error? And send me log file

Nothing show from console and logfile is just : 
12-06-2024 19:31:26 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:31:34 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:32:03 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:33:54 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:34:51 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:35:49 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:36:27 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:38:56 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:40:20 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:41:25 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:42:07 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:42:42 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 19:43:27 INFO  AudiobookConverter:81 - Initialising application

**Comment by SeMuh83** [comment] 2024-06-13 06:54
> > All works when i test. Could you run app from console and show if there is any error? And send me log file
> 
> Nothing show from console and logfile is just : 12-06-2024 19:31:26 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:31:34 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:32:03 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:33:54 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:34:51 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:35:49 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:36:27 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:38:56 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:40:20 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:41:25 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:42:07 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:42:42 INFO AudiobookConverter:81 - Initialising application 12-06-2024 19:43:27 INFO AudiobookConverter:81 - Initialising application

How to do that on windows?

**Comment by fabiwan** [comment] 2024-06-13 08:20
just check logfile  in %appdata%\6.5.1\AudioBookConverter.log

**Comment by joespinoza** [comment] 2024-06-13 14:27
31-05-2024 16:24:40 INFO  AudiobookConverter:81 - Initialising application
31-05-2024 16:25:07 INFO  AudiobookConverter:81 - Initialising application
31-05-2024 16:25:22 INFO  AudiobookConverter:81 - Initialising application
31-05-2024 16:25:52 INFO  AudiobookConverter:81 - Initialising application
31-05-2024 16:27:14 INFO  AudiobookConverter:81 - Initialising application
31-05-2024 16:27:57 INFO  AudiobookConverter:81 - Initialising application
31-05-2024 16:32:22 INFO  AudiobookConverter:81 - Initialising application

**Comment by SeMuh83** [comment] 2024-06-14 12:13
Same

12-06-2024 16:25:50 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 16:26:29 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 16:26:53 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 16:28:01 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 16:36:30 INFO  AudiobookConverter:81 - Initialising application
12-06-2024 16:36:35 INFO  AudiobookConverter:81 - Initialising application
13-06-2024 08:49:26 INFO  AudiobookConverter:81 - Initialising application
14-06-2024 14:12:20 INFO  AudiobookConverter:81 - Initialising application

**Comment by fabiwan** [comment] 2024-06-14 16:10
How can we help ? I am not a developer. I cloned the project and installed microsoft-jdk-21.0.3-windows-x64.msi, gradle-8.8-bin.zip, and apache-maven-3.9.7-bin.zip. I asked ChatGPT how to build a Java project, and it told me to run 'mvn clean install', but it crashes because not resolve dependencies 

`[ERROR] Failed to execute goal on project audiobookconverter: Could not resolve dependencies for project uk.yermak:audiobookconverter:jar:#{APP_VERSION}#: The following artifacts could not be resolved: org.openjfx:javafx-controls:jar:${javafx.platform}:21.0.3 (absent), org.openjfx:javafx-fxml:jar:${javafx.platform}:21.0.3 (absent), org.openjfx:javafx-graphics:jar:${javafx.platform}:21.0.3 (absent), org.openjfx:javafx-swing:jar:${javafx.platform}:21.0.3 (absent), org.openjfx:javafx-media:jar:${javafx.platform}:21.0.3 (absent), org.openjfx:javafx-base:jar:${javafx.platform}:21.0.3 (absent): Could not find artifact org.openjfx:javafx-controls:jar:${javafx.platform}:21.0.3 in github-mvn-repo-ffmpeg-cli-wrapper-snapshot (https://github.com/yermak/ffmpeg-cli-wrapper/raw/mvn-repo/) -> [Help 1]
`
 I think I'm doing something wrong. Could you please provide a mini tutorial on how to build the project on Windows? 
Thanks

**Comment by yermak** [comment] 2024-06-15 10:50
All, considering it's not issue for everyone, I would assume it's something to do with your own settings/environment, maybe you have some new antivirus database, etc.

I will make test build with more detailed logging by default, so we could jointly look for issue

**Comment by pegu-oss** [comment] 2024-06-20 21:14
Hello,

the problem is caused by a locale that is not _English_.
In this case, a **java.util.MissingResourceException** occurs in **getBundleWithFallback**

You can recreate the problem by replacing this line in the **start** method:
`Locale defaultLocale = Locale.getDefault();` 
through 
`Locale defaultLocale = new Locale("de", "DE");`

**Comment by pegu-oss** [comment] 2024-06-21 07:44
Here is a fix:

```
private ResourceBundle getBundleWithFallback(Locale locale) {
	ResourceBundle bundle = null;

	ResourceBundle.Control control = ResourceBundle.Control.getControl(ResourceBundle.Control.FORMAT_DEFAULT);

	try {
	   bundle = ResourceBundle.getBundle("locales/messages", locale, control);
	} catch (MissingResourceException e) {
            logger.error("Error getBundle", e);
        }

	return bundle != null ? bundle : ResourceBundle.getBundle("locales/messages", new Locale("en"), control);
    }
```

**Comment by yermak** [comment] 2024-06-21 08:42
> Here is a fix:
> 
> ```
> private ResourceBundle getBundleWithFallback(Locale locale) {
> 	ResourceBundle bundle = null;
> 
> 	ResourceBundle.Control control = ResourceBundle.Control.getControl(ResourceBundle.Control.FORMAT_DEFAULT);
> 
> 	try {
> 	   bundle = ResourceBundle.getBundle("locales/messages", locale, control);
> 	} catch (MissingResourceException e) {
>             logger.error("Error getBundle", e);
>         }
> 
> 	return bundle != null ? bundle : ResourceBundle.getBundle("locales/messages", new Locale("en"), control);
>     }
> ```

Great thanks! Will release fix today!

**Comment by yermak** [comment] 2024-06-21 19:49
To all users using locales other then English, as you see I started localisation of the application, as part of resolving issue #530

Here is the file with English texts, I will be happy to accept you suggestions for other languages (surely, I could use translator - but I will not be able to verify it properly)
https://github.com/yermak/AudioBookConverter/blob/development/src/main/resources/locales/messages_en.properties

**Comment by fabiwan** [comment] 2024-06-21 21:03
it works for me (6.5.2)
Thank you both!

**Comment by yermak** [comment] 2024-06-21 22:55
> it works for me (6.5.2) Thank you both!
> 
> edit: french windows here, it ask me to download new version from steam, but i don't use steam ;)

All kudos should go to @pegu-oss. I was too busy with a day job to investigate.

**Closed by yermak** 2024-06-21 22:55 UTC
Labels: can't reproduce
