### ISSUE TITLE
Cut-off frequencies

### ISSUE THREAD

**Issue by ice44** [yermak/AudioBookConverter#184] opened 2020-12-27 03:42 UTC
How do I disable this setting? I keep getting glitched and corrupted audio tracks no matter the cut-off value.

**Comment by yermak** [comment] 2020-12-27 14:10
Hi,
In current version - it's not possible.
I will add this in the future.

Are you sure, that's exactly cut-off setting which causes the glitches?

**Comment by ice44** [comment] 2020-12-29 07:30
I am not sure now, I have re-encoded with VBR and the issue is still present. I am not sure what is causing it, when I use AAC Audiobook Creator there is no issue, but I do not like because it artificially limits the m4b file size while your program does not, I can keep my audiobook as a single file and do not have to split it into parts which is what I like.

**Comment by yermak** [comment] 2020-12-29 12:23
@ice44,

I assume this only happens with one book or with all of them?

As a workaround i can suggest to try to create your book in Audiobook Creator and then import all parts created into my AudioBookConverter - it should be able to merge them without re-encoding and preserving chapters and art work

If you see this behaviour with all of the books you tried, share link to one of them to %mynicname% at gmail dot com - i will try debug the root cause...

**Comment by yermak** [comment] 2021-01-03 22:49
@ice44,

I added option to disable cutoff  - this will be released in next version.

However, please note that in some conditions codec can do cutoff automatically and I'm not aware about the way of overriding this.

**Closed by yermak** 2021-01-03 22:49 UTC
