### ISSUE TITLE
M4b M4b Convertion from a High Bit Rate to a Lower Bite does not work.

### ISSUE THREAD

**Issue by OldScotsman** [yermak/AudioBookConverter#493] opened 2023-10-20 08:17 UTC
When finished to editing the chapters in an M4b file I wish to convert the bit rate from 128 Kb to 64 Kb.  The editing works but I can't change the bit rate to anything.
Can you help.
OldScotsman

**Comment by yermak** [comment] 2023-11-16 19:15
Duplicate of #494

**Closed by yermak** 2023-11-16 19:15 UTC
