### ISSUE TITLE
Job Process will not start

### ISSUE THREAD

**Issue by dstory1** [yermak/AudioBookConverter#25] opened 2019-07-15 14:47 UTC
After I add the files, audiobook information and artwork, and using the standard settings, after I click start and the saved file name, nothing happens. The queue remains empty, and I see no activity.

**Comment by user2223** [comment] 2019-08-03 20:17
I have this problem with some files too. One reason i figured out (at least i guess so) were too long path lengths.

**Comment by aterriblegamer** [comment] 2019-08-22 21:11
Same issue. This worked for several books and now all of a sudden its broken. Now this path isn't even working
E:\Download\Skin Game\Skin Game 01of14.mp3
.
.
.
E:\Download\Skin Game\Skin Game 14of14.mp3

**Comment by Mfdas** [comment] 2019-09-02 01:40
I was having a similar problem.  Make sure that all the files in the queue are audio files.  I was accessing my NAS on a Windows machine and someone with a Mac had accessed it previously and created .DS_STORE and .AppleDouble files in with the MP3s and when I dragged the folder in, it copied those as well.  Once I removed those it worked for me.  The program might benefit from adding a filter to only allow files with known audio file extensions.

**Comment by aterriblegamer** [comment] 2019-09-05 18:34
It was not file type, but something in the file name that would not let the process begin. Used MP# Tag to rename the files and everything kicked off. Nothing looked odd in the file name, so not suire what was going on here.

**Comment by yermak** [comment] 2019-09-09 07:25
> I was having a similar problem. Make sure that all the files in the queue are audio files. I was accessing my NAS on a Windows machine and someone with a Mac had accessed it previously and created .DS_STORE and .AppleDouble files in with the MP3s and when I dragged the folder in, it copied those as well. Once I removed those it worked for me. The program might benefit from adding a filter to only allow files with known audio file extensions.

Hi, could you please clarify your scenario - did you drag-n-drop files to app or used button to add them?

**Comment by yermak** [comment] 2019-09-09 07:27
> It was not file type, but something in the file name that would not let the process begin. Used MP# Tag to rename the files and everything kicked off. Nothing looked odd in the file name, so not suire what was going on here.

Hi, could you share original file somewhere - so I could test it? Did it contain any not latin symbols?

**Comment by Mfdas** [comment] 2019-09-09 07:32
> 
> 
> > I was having a similar problem. Make sure that all the files in the queue are audio files. I was accessing my NAS on a Windows machine and someone with a Mac had accessed it previously and created .DS_STORE and .AppleDouble files in with the MP3s and when I dragged the folder in, it copied those as well. Once I removed those it worked for me. The program might benefit from adding a filter to only allow files with known audio file extensions.
> 
> Hi, could you please clarify your scenario - did you drag-n-drop files to app or used button to add them?

I dragged and dropped a whole folder of files from windows explorer.  I thought it was all mp3s, but the MacOS hidden ones were in there as well and I didn't notice them at first.

**Comment by yermak** [comment] 2019-09-09 07:45
> I dragged and dropped a whole folder of files from windows explorer. I thought it was all mp3s, but the MacOS hidden ones were in there as well and I didn't notice them at first.

Thanks. I know where to fix it.

**Comment by Mfdas** [comment] 2019-09-11 07:25
I've had this issue again with different circumstances.  It's just .mp3 files listed in the program, and I've made sure that there are no strange characters by renaming them to just a number and .mp3, but whatever I do it will not start converting them.  I've verified that the files play in VLC, so I don't think they're corrupt.

**Comment by Mfdas** [comment] 2019-09-21 22:01
It looks like the files I was trying to convert just didn't have any tag data associated with them at all.  Using MP3tag to add the data allowed them to be converted, thanks.

**Comment by Cassock** [comment] 2020-01-01 22:43
Same issue here: first book went flawlessly, second and third will not start at all. Tried renaming, editing a few fields, deleting tags entirely, recreating the tags, all with no luck. Are there logs available that I can look through to see what's preventing this from starting?

**Comment by Cassock** [comment] 2020-01-01 23:48
Deleting AudioBookConverter-V3.properties seems to fix it and at least let the process start, but now I'm stuck at "Merging chapters..." for about 30 minutes (conversion only took about 2 mins).

**Comment by yermak** [comment] 2020-01-02 13:01
Hi all,
Unfortunately, the loging is not fully implemented. So, if you could reproduce the issue with just couple of chapters/file not the full book, i would recommend upload them to some cloud storage and share the links with me in separate issue.
Alternative way to reach me use my github account name @gmail.com.

**Comment by Cassock** [comment] 2020-01-02 13:06
After initially deleting the app .properties file and restarting, I've had no issues (even with the same books that failed earlier). I have also switched to a different workflow where the source and destination are the same, so maybe that helped.

**Comment by yermak** [comment] 2020-05-26 08:41
I close this issue as problem was related to old version

**Closed by yermak** 2020-05-26 08:41 UTC

**Comment by seanyar** [comment] 2021-04-11 18:54
I still have this issue. Using ver 5.5.18. Everything was working fine until today. Just as other comments above, after dragging and dropping couple of MP3 files, nothing happens when you click on start. Stripped all tags and tried re-adding tags and attempted to convert - no luck. Each MP3 files on their own, plays just fine.
