### ISSUE TITLE
Weird things with chapters

### ISSUE THREAD

**Issue by TDietrich99** [yermak/AudioBookConverter#428] opened 2022-07-13 10:23 UTC
Okay, so i added a total of 113 Chapters (mp3). But now when i hit "start" or "chapters" there are suddenly 12k+ chapters which are just repetitions of chapters 1-113. this obviously results in audiobooks being way longer and bigger than needed.
these "new" chapters also dont show up in the queue
![Screenshot 2022-07-13 121434](https://user-images.githubusercontent.com/107218383/178710195-c1383afd-8411-46cc-884e-820383435c95.png)
![Screenshot 2022-07-13 121207](https://user-images.githubusercontent.com/107218383/178709553-392ce317-5b51-4da2-ba8e-227956a65a2a.png)
![Screenshot 2022-07-13 122746](https://user-images.githubusercontent.com/107218383/178713304-086df541-7b3c-480d-9e1b-9ae39132a810.png)

this is the second audiobook i tried convert that way. the first worked like charm

edit: i also dont know where chapter 1 and 115 come from, i only imported 113 files

Version: 6.1.1 (portable)

**Comment by DrReddP** [comment] 2022-07-19 21:01
I have what I think is a similar issue.. The book I'm doing has 117 chapters. It's putting the wrong audio with specific chapters. Like, I went to listen to it, and the first four chapters all had the proper titles, but they all had the audio from chapter 1. It didn't do this for every single chapter, but it did it for several.

I assumed I was trying to large of a batch, so I tried doing just a "part one" with only 13 chapters in it, and it did the exact same thing.

**Comment by yermak** [comment] 2022-07-19 21:38
I will look into this in few days.
As an option you could try different version, i.e. Latest 5.x.x to see if this regression or not, earlier i was able to convert book with more then 100 chapters... Or i will try in few days

**Comment by TDietrich99** [comment] 2022-07-19 21:40
> I have what I think is a similar issue.. The book I'm doing has 117 chapters. It's putting the wrong audio with specific chapters. Like, I went to listen to it, and the first four chapters all had the proper titles, but they all had the audio from chapter 1. It didn't do this for every single chapter, but it did it for several.
> 
> I assumed I was trying to large of a batch, so I tried doing just a "part one" with only 13 chapters in it, and it did the exact same thing.

i havent fixed it yet, but i found the issue at least. the mp3 files i was using were cut from a larger mp3 file, which apparently had chapter metadata. so the cut parts had this metadata as well, which ABC was reading it seems. so it essentially had data for ~100h worth of chapters in a ~10min file 

i am sure there is a program out there, that can give you a metadata free mp3, as for ABC maybe it should check if the length of the file matches the data from the chapters itself, and if not offer to clear all of this metadatajunk

**Comment by DrReddP** [comment] 2022-07-19 21:44
> 

Again, it did the same thing when I tried it with only 13 chapters. Is there a quick and easy way to just strip the metadata?

**Comment by TDietrich99** [comment] 2022-07-19 21:52
> > 
> 
> Again, it did the same thing when I tried it with only 13 chapters. Is there a quick and easy way to just strip the metadata?

maybe try [ID3Kill](https://www.ghacks.net/2008/12/21/id3-tag-remover/)?

**Comment by DrReddP** [comment] 2022-07-19 21:53
> I will look into this in few days. As an option you could try different version...

Yeah looks like 5.6.2 isn't having this issue, at least not with smaller books.

**Comment by yermak** [comment] 2022-09-25 19:49
@TDietrich99
If you still have sample of mp3 with chapter meta data, could you please share with me by sending link to my_nick_name at gmail.
chapters in mp3 are not very standard, i definitely could strip them off in the future.

**Comment by yermak** [comment] 2024-05-30 14:50
I will not be able to reproduce it w/o source audio files. Closing the issue

**Closed by yermak** 2024-05-30 14:50 UTC
