### ISSUE TITLE
"Error" joining multiple .mp3 files

### ISSUE THREAD

**Issue by raineedust** [yermak/AudioBookConverter#422] opened 2022-06-21 16:34 UTC
I am grateful for this app's existence. It's a blessing for audiobooks, although the failure rate trying to join multiple similar files is much more often than I preferred.

As per the attached log, I tried to join multiple .mp3 files that are related to a single book, and it just fails. Can anyone help take a look at what's wrong?

Additionally as a feedback, I would appreciate if the GUI produce some meaningful error messages along with its common solutions listed on the Wiki, rather than just an "Error!", given how common this issue is (from my personal experience, including with .m4a/b)

[AudioBookConverter.log](https://github.com/yermak/AudioBookConverter/files/8950716/AudioBookConverter.log)

**Comment by yermak** [comment] 2022-07-10 10:34
@raineedust ,
Thanks for reporting. I assume you merged mp3s into single mp3.
I can reproduce it - will be fixed soon.

**Comment by yermak** [comment] 2022-07-10 13:09
I will keep it here for the record. 
This is due to JDK bug https://bugs.openjdk.org/browse/JDK-8131908 which they refer as Windows problem.
Windows considers this is correct approach... in practice program can't run in Windows and Mac without hack. It was my fault not to fix it reliably as I was hacking for mac to win and back, and for some time this bug appeared on one or another platform :(

**Comment by raineedust** [comment] 2022-07-15 04:43
Thank you for bringing your attention to the issue! Sadly I am a frontend webdev and never worked with JDK before so I can’t contribute, but my best wishes go to you!

**Comment by yermak** [comment] 2022-07-15 13:57
@raineedust , sorry I forgot to close the bug. It was fixed in 6.1.1.
Please let me know if issue is still there.

**Closed by yermak** 2022-07-15 13:57 UTC
Labels: bug
