### ISSUE TITLE
BUG? - Split/Combine by accident - no time info

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#84] opened 2020-07-23 16:32 UTC
So I was naming chapters manually and I accidentally hit split.  So I hit combine and there was some differences afterwards in the way it displayed on the screen afterwards.  Not sure if this means the files aren't pulling in or not.  

I did notice that there were TWO part 2's with the files in question.  I highlighted ALL the files then clicked Combine.  Then noticed there were duplicate chapters so REMOVED the final set.   I'm not sure if both sets of chapters had the timestamps or not.

<img width="380" alt="Capture" src="https://user-images.githubusercontent.com/57738712/88312746-84bde700-cce0-11ea-901f-386041b6891d.PNG">

**Comment by yermak** [comment] 2020-07-23 18:03
Hey,
Yes, it's definitely a bug.
I was able to reproduce after slitting just imported book it creates 2 part 2's.
If you remove one of them - chapters are removed, further bahaviour is unpredictable. 

That's important issue. Thank you for reporting.

**Comment by yermak** [comment] 2020-07-23 19:07
Fixed and will be released in version 5.3.
I fixed root cause - duplication of parts, all other consequences which you observe are results of earlier error.
time is displayed correctly - 0, as there is no file in chapter. Chapter with no file should not exist.

**Closed** 2020-08-19 05:30 UTC
Labels: bug, todo
