### ISSUE TITLE
Clicking "Start" Does Nothing

### ISSUE THREAD

**Issue by silentArtifact** [yermak/AudioBookConverter#379] opened 2022-02-17 12:32 UTC
Using the current Steam build. The start button is unresponsive. Reinstalling doesn't seem to fix it.

**Comment by yermak** [comment] 2022-02-17 12:43
Hi, what OS do you use?
Will you be able to share logs?

**Comment by silentArtifact** [comment] 2022-02-17 13:00
Windows 10, and sure! Where would I find them?

**Comment by yermak** [comment] 2022-02-17 17:25
For current steam version for windows
C:\Users\%USERNAME%\Application Data\AudiobookConverter-6.0.0\AudioBookConverter.log

Additionally/Alternatively you may upload your files to some cloud storage and share with me, so i could reproduce.

Link to files could be sent to my username @ gmail

**Comment by rs-taylor** [comment] 2022-03-02 14:40
Having the same issue, worked ok then START just didn't do anything. Windows 11 64bit and 6.0.1 Github download.
Installed older 5.6.2 (Github) and that's working just fine.

**Comment by tusculumgolfer** [comment] 2022-05-27 12:19
Having same issues with 6.0.1

**Comment by yermak** [comment] 2022-06-02 07:59
> Having the same issue, worked ok then START just didn't do anything. Windows 11 64bit and 6.0.1 Github download. Installed older 5.6.2 (Github) and that's working just fine.

I have not tested window 11 yet. Probably it's time.

**Comment by ClassH36** [comment] 2022-06-08 17:27
I had this issue today.  Figured out that there was a track tag on the mp3 that was messing it up (was track 1/436) even though it was a single mp3.  I put the file in mp3 tag, reset the track number, then tried again and it converted fine.

**Comment by yermak** [comment] 2022-06-09 12:01
@ClassH36,
which version did you use for this? 
Just to reconfirm you had mp3 with tag exactly "track" (not "track number") and this tag contained "1/436" and it prevented conversion to start?

**Comment by ClassH36** [comment] 2022-06-09 12:12
> 

Version 6.1.0
The track field was 1/436 instead of a normal whole number. The only thing I changed was to change it to 1 in MP3 Tag and saved the tags back to the file.  Reloaded it and worked fine.  I had tried reloading and restarting multiple times and that 1 file would not process until I did that.

**Comment by yermak** [comment] 2022-06-09 12:38
@ClassH36, thanks a lot will try to reproduce.
1/436 -is actually not unusual thing, iTunes saves tracks information this way. 

However, my concern that Mp3 Tag actually fixed other tags (implicitly) rather then track field was a problem...
If you could do me a favour, and share this file via some cloud link or directly to my username at gmail
(unless it's something sensitive)

Thanks.

**Comment by yermak** [comment] 2022-06-10 08:46
I found what causing this issue, as 4294967295 can fit into integer, so, long number should be used.
This will be fixed, but more importantly error at this stage was causing program to break w/o clear message. So, i will have a look in more detail how to make it more robust against incorrect tags or just errors at tag parsing phase.

**Comment by vidtech200** [comment] 2022-08-14 05:05
I am experiencing the same problem with Win10 & 6.1.1, nothing will "start" with press of the start button.   It was a directory with a single mp3 file, a que file, and a jpg (cover) file.  Thinking it was just this book, tried the next in the series with no go as well.   My first google read was here on github (Issue #25), so I tried some of the thoughts/fixes from there...
- it was a nested directory, so I copied the mp3 only into a 2 letter directory off of root, with a short file name (in case name string was too long); no-go
- nothing looked out of the ordinary with the file (VLC played it fine), but tried renaming it w/ mp3tag as some had suggested worked; no-go
- then I thought, hey, let's back up to one I'd already converted (was keeping originals on separate drive until conversions were done, and the exact same mp3 I had converted w/ no problem yesterday will also not start, so assuming that yes, something broke the program.

Subsequently found this more current thread (#379), so thought it's been a month or two since Jun 10th, so didn't know if there were any new directions on how to proceed yet...     and yes, all of your time and effort in this is definitely appreciated...  I went ahead and bought it on steam, figured 5 bucks was the least I could do to support your efforts.  I'll install that next to see if that fixes it, but wanted to weigh in that 6.1.1 still has this issue.

**Comment by yermak** [comment] 2024-05-31 21:10
> I found what causing this issue, as 4294967295 can fit into integer, so, long number should be used. This will be fixed, but more importantly error at this stage was causing program to break w/o clear message. So, i will have a look in more detail how to make it more robust against incorrect tags or just errors at tag parsing phase.

I actually fixed int to long some time ago. So, I close this bug as fixed also start problem should also be fixed by now.

**Closed by yermak** 2024-05-31 21:10 UTC
